import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles.css";
import { DarkModeProvider } from "./DarkModeContext"; // Adjust the import path

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bachelor's Thesis",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DarkModeProvider>{children}</DarkModeProvider>
      </body>
    </html>
  );
}
